routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'HomeController@index');

Route::get('login','LoginAppController@index');
Route::post('login','LoginAppController@login');
Route::get('logout','LoginAppController@logout');

Route::post('dosen/{id}','ManageDosenController@postLocation')->name('dosen.location.update');
Route::resource('dosen','ManageDosenController');
Route::get('filterkrs',"DemoKrsController@filterKrs");
Route::get('krs','DemoKrsController@index');
Route::post('krs','DemoKrsController@storeKrs');

Route::get('approve','ApprovalKrsController@index');
Route::get('approve/{nim}','ApprovalKrsController@show');
Route::post('approve/{nim}','ApprovalKrsController@setujui');

app/Http/Controllers/DosenController.php
<?php

namespace App\Http\Controllers;

use App\Api;
use App\LokasiDosen;
use Illuminate\Http\Request;

class DosenController extends Controller
{

    const DOMISILI_KOTA = "KOTA GORONTALO";
    const DOMISILI_BONE = "BONE BOLANGO";
    const DOMISILI_KAB = "KAB. GORONTALO";
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id = 1;
        $param['kodefak'] = '05';
        //$param['kodejur'] = '57401';
        $response = Api::getService('getalldosen',$param);
        $dosen = [];
        for($i = 0; $i < count($response['data']); $i++){
            for($j = 0; $j < count($response['data'][$i]['DOSEN']); $j++){
                $dosen[] = $response['data'][$i]['DOSEN'][$j];

            }
        }

        for ($x = 0; $x < count($dosen); $x++){
            $lokasi = LokasiDosen::where('nidn',$dosen[$x]['NIDN'])->first();
            if($lokasi){
                $dosen[$x]['LATITUDE'] = $lokasi->latitude;
                $dosen[$x]['LONGITUDE'] = $lokasi->longitude;
            }else{
                $dosen[$x]['LATITUDE'] = null;
                $dosen[$x]['LONGITUDE'] = null;
            }

        }

        return $dosen;
    }

    public function getProdi()
    {
        $id = 1;
        $param['kodefak'] = '05';
        //$param['kodejur'] = '57401';
        $response = Api::getService('getalldosen',$param);

        return $response;
    }

    public function getDosenByProdi($kdprodi)
    {
        $param['kodefak'] = '05';
        //$param['kodejur'] = '57401';
        $param['kodeprodi'] = $kdprodi;

        $response = Api::getService('getalldosen',$param);
        $dosen = $response['data'][0]['DOSEN'];

        $res = [];
        for ($x = 0; $x < count($dosen); $x++){
            $lokasi = LokasiDosen::where('nidn',$dosen[$x]['NIDN'])->first();
            if($lokasi){
                $dosen[$x]['LATITUDE'] = $lokasi->latitude;
                $dosen[$x]['LONGITUDE'] = $lokasi->longitude;
                $res[] = $dosen[$x];
            }else{
                $dosen[$x]['LATITUDE'] = null;
                $dosen[$x]['LONGITUDE'] = null;
            }

        }

        return $res;
    }

    public function getDosenByDomisili($domisili)
    {
        $id = 1;
        $param['kodefak'] = '05';
        //$param['kodejur'] = '57401';
        $response = Api::getService('getalldosen',$param);
        $dosen = [];
        for($i = 0; $i < count($response['data']); $i++){
            for($j = 0; $j < count($response['data'][$i]['DOSEN']); $j++){
                $dosen[] = $response['data'][$i]['DOSEN'][$j];

            }
        }

        $res = [];
        for ($x = 0; $x < count($dosen); $x++){
            $lokasi = LokasiDosen::where('nidn',$dosen[$x]['NIDN'])
                ->where('kabkot',$domisili)
                ->first();

            if($lokasi){
                $dosen[$x]['LATITUDE'] = $lokasi->latitude;
                $dosen[$x]['LONGITUDE'] = $lokasi->longitude;
                $dosen[$x]['DOMISILI'] = $lokasi->kabkot;
                $res[] = $dosen[$x];
            }else{
                $dosen[$x]['LATITUDE'] = 0.0;
                $dosen[$x]['LONGITUDE'] = 0.0;
                $dosen[$x]['DOMISILI'] = "";
            }

        }

        return $res;
    }




    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dosen/index.blade.php
@extends('layouts.master')

@section('breadcrumbs')

    <ol class="breadcrumb">
        <li><a href="index.html">Admin Panel</a></li>
        <li><a href="#">Dashboard</a></li>
        <li class="active">Overview</li>
        <li><a href="sign-in.html">Sign In Form</a></li>
    </ol>

@endsection

@section('content')

<h1>Daftar Dosen</h1>

<div class="table-responsive">
    <h4 class="margin-bottom-15">New Users Table</h4>
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th>#</th>
            <th>Fakultas</th>
            <th>Prodi</th>
            <th>Edit</th>

        </tr>
        </thead>
        <tbody>
        @foreach($response['data'] as $prodi)
        <tr>
            <td>{{ $id }}</td>
            <td>{{ $prodi['FAKULTAS'] }}</td>
            <td>{{ $prodi['PRODI'] }}</td>
            <td><a href="{{ url(route('dosen.show',$prodi['KODEPRODI'])) }}" class="btn btn-info">Edit</a></td>


        </tr>
        <?php $id++ ?>
            @endforeach



        </tbody>
    </table>

@endsection

resources/views/dosen/show.blade.php
@extends('layouts.master')

@section('breadcrumbs')

    <ol class="breadcrumb">
        <li><a href="index.html">Admin Panel</a></li>
        <li><a href="#">Dashboard</a></li>
        <li class="active">Overview</li>
        <li><a href="sign-in.html">Sign In Form</a></li>
    </ol>

@endsection

@section('content')

<h1>Daftar Dosen</h1>

<div class="table-responsive">
    <h4 class="margin-bottom-15">New Users Table</h4>
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th>#</th>
            <th>NIDN</th>
            <th>NIP</th>
            <th>Nama</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Domisili</th>
            <th>Action</th>

        </tr>
        </thead>
        <tbody>
        @foreach($data as $dosen)
        <tr>
            <form action="{{ url(route('dosen.location.update',$dosen['NIDN'])) }}" METHOD="POST">
                {{ csrf_field() }}
            <td>{{ $num }}</td>
            <td>{{ $dosen['NIDN'] }}</td>
            <td>{{ $dosen['NIP'] }}</td>
            <td>{{ $dosen['NAMA'] }}</td>
            <td><input type="text" name="latitude" VALUE="{{  ($res = \App\LokasiDosen::where('nidn',$dosen['NIDN'])->first() ) ? $res->latitude : '' }}"></td>
            <td><input type="text" name="longitude" VALUE="{{  ($res = \App\LokasiDosen::where('nidn',$dosen['NIDN'])->first() ) ? $res->longitude : '' }}"></td>
            <td>
                <select name="kabkot">
                    <option value="KOTA GORONTALO">KOTA GORONTALO</option>
                    <option value="KAB. GORONTALO">KAB. GORONTALO</option>
                    <option value="BONE BOLANGO">BONE BOLANGO</option>
                    <option VALUE="BOALEMO">BOALEMO</option>
                    <option value="POHUWATO">POHUWATO</option>
                    <option value="GORONTALO UTARA">GORONTALO UTARA</option>
                </select></td>

            <td>

                    <button type="submit" class="btn btn-info">SIMPAN</button>

            </td>
            </form>

        </tr>
        <?php $num++ ?>
            @endforeach



        </tbody>
    </table>

@endsection